[server]
name = "data-app"
version = "0.1.0"

[web]
# 服务器ip 端口
address = "0.0.0.0:8001"
# 开启压缩
compress = true
# 管理员账户
admin_name = "admin"
# 管理员密码
admin_password = "admin"

[log]
dir = "logs"
# 允许操作日志
enable_oper_log = true
# 日志级别
level = "DEBUG" #  TRACE DEBUG  INFO  WARN ERROR

[database]

# uri = 'mysql://root:password@192.168.1.11:13306/db'
# uri = 'mysql://root:password@127.0.0.1:13306/db'
# uri = 'postgres://postgres:password@192.168.1.11:15432/db'
uri = 'sqlite://./data/rss-data.sqlite3?mode=rwc'
# uri = 'mysql://root:password@localhost:3306/db'
